### ISSUE TITLE
Cannot use bluetooth barcode scanner to connect to KDS 3.0.3 beta

### ISSUE THREAD

**Issue by kadreher** [kddart/kdsmart-apks#12]
Greetings,

I was excited to see that KDS 3.0.3 had arrived. I am trying to connect to a bluetooth scanner to see if I can jump to the right plot, but when I am in the plots scoring and supposed to be selecting which device to connect to, I try to click on the right device. It tries to connect for about 1 second and then I get a message saying "Connection Timeout."

I checked with another app and I could get the barcode to be typed into the text box, so I know that the barcode reader is properly paired. Can you please confirm if you have checked in 3.0.3 if we can use a bluetooth-paired barcode reader to jump to the right plot?

I have also asked @acra1907 to test this, so I hope that she can record her experiences in this issue, too.

Thank you.

Sincerely,
kate

**Comment by acra1907** [comment]
Hello all

I had exactly the same results than Kate. I also checked that the barcode reader is properly paired. 

Thanks!
Carolina

**Comment by manil007** [comment]
Hey kate, 
I really appreciate you testing beta version and I am very thankful for that

**Comment by manil007** [comment]
Also i think you asked about how to add Non zip files in github.
You drag and drop them, like the one above.

There will be 3.0.4 release tonight IST time. 
Its only for few more non bluetooth related bug fixes.
Thanks
..M..

**Comment by kadreher** [comment]
Hi Manil,

Thanks for your message.

1) Regarding the files in Github . . . if I try to drag and drop .csv files it says that file type is not supported so I have to zip .csv files to be able to upload them. Can you drag and drop .csv files directly onto these Github issues? If so, I wonder why I can’t. I think that Carolina experienced the same issue.

2) I am a little confused about the problems that we are having with the barcode reading functionality in 3.0.3. The release notes for 3.0.3 say a few things about new barcode functionalities that are in place in 3.0.3. Reading these notes today made me realize that I actually did not try to jump to other plots initially using the list mode (which is explicitly mentioned in the release notes).  I was trying from the standard plot mode. So, I thought that was possibly the problem. (Should we be able to jump in the normal plot mode? Or just the list mode?)

So then I tried to test it from the list mode today. Here are the results:

a) It did not work when I tried it just from the list view with the blue tooth device definitely connected to the phone. I tried to jump to a plot using a barcode that I had created in KDX and tried to pass to my phone. Instead of jumping, It typically just popped up the message asking if I wanted to stop scoring.

b) Then I tried entering a numerical trait input box and I could use the barcode scanner to input the number values, so the scanner was clearly paired

c) Then I tried to return to the list mode to try to jump to the right plot. But, I realized that I might not have selected the correct option on the menu in the upper right. So, I tried to click on the message (in Spanish) that seems to say that the Scanner is turned on. This caused the software to stop functioning and I was given the option to submit an error report which I did. But, just in case it was a fluke, I tried again and got the same result.

So, can you please let us know what phone/tablet device and version of Android and what barcode scanner you tested these newly released functionalities on where they worked properly?  We’d like to know if there is something that we are doing wrong or if we are having problems based on our hardware or Android version?

** And based on your message about 3.0.4 . . . should we assume that we can jump between plots based on barcodes generated by KDX in the list and/or plot mode?

Many thanks,
kate

**Comment by manil007** [comment]
Hey Kate thanks for the message again.
First of all I think you mean
List Mode = SpreadSheet View.
Plot Mode = Path View.
Its better if we use same names, since it gets confusing.

I am sure after reading your a and b  that your barcode scanner is not in SPP mode.
you need to configure these devices to SPP mode.

I sent a link in the file i uploaded before there are two main modes of Bluetooth scanners
one is SPP and other is HID

in HID mode which we dont want, a bluetooth  scanner works as a keyboard which seems like what we want it to do though this results in that weird behaviour of just throwing text out on any text box it finds on the screen. KDSmart doesnt receive this scanned text in the correct manner.

I am concerned that HID mode actually crashed the application, this shouldnt have happened so apologies. I will test this in future releases.

For now SPP mode is what you want, try finding the manuals of the scanner online and configure the device properly, This SPP mode requirement will go in online doc.

Both Views support Barcodes Scanning now, just the spreadsheet view doesnt work with Trait barcodes. The reason behind that is we are never sure which plot is the current plot as all 
plots are available at the same time. So we are not sure which Sample Measurement Trait Dialog to 
pop up. We will find a solution soon for this.

Let me know how it goes.

I think you can drag and drop TXT files not CSV. I can then convert them back to CSV.

Also i have a new nickname its called "..M.." , I am honoured.
Thanks
..M..

**Comment by kadreher** [comment]
Thank you, thank you, thank you!!

Now, I can get it to work! I entered it into SPP mode and now I can jump to the right plots.

I am very grateful for your trouble-shooting! And, the good news, too, is that I did not get the error of trying to connect with the scanner.

I have not tried this with user-defined barcodes yet . . . only with barcodes generated from KDX. But, Carolina and I can try that test next now that we have the baseline working.

Thanks so much again!

Sincerely,
kate

**Comment by manil007** [comment]
I am glad kate,

I have a new issue on our internal Redmine, with the subject 
KDSmart breaks when HID bluetooth barcode devices are connected

Barcodes with different sources (Non KDX) should work as expected.
just select the settings in Setting screen. 
you cant miss that.


I am closing this issue now.
Thanks
..M..

**Comment by kadreher** [comment]
Hi Manil,

Thanks very much. Unfortunately, I cannot seem to get to the setting screen. Every time that I click on the icon, the software stops working. I sent an error report about that, too.

Do you mean that we can set the barcode to read another value under the general settings tab?

Or, do you mean some kind of settings within the trial.

Thanks again, Manil.

Saludos,
kate
